language: node_js
os:
- linux
- osx
- windows
dist: xenial
cache:
  directories:
  - node_modules
node_js:
- node
- 8.9.3 # VSCode 1.26.0
sudo: false
matrix:
  fast_finish: true
before_install:
- if [ $TRAVIS_OS_NAME == "linux" ]; then
    export CXX="g++-4.9" CC="gcc-4.9" DISPLAY=:99.0;
    sh -e /etc/init.d/xvfb start;
    sleep 3;
  fi
install:
- yarn
- yarn vscode:install
- yarn vscode:prepublish
script:
- yarn test
notifications:
  email: false
