language: node_js
os:
- linux # VSCode tests fail without an error message/stack trace
- osx
- windows
dist: xenial
cache:
  directories:
  - node_modules
node_js:
- node
- 12.22.7 # VSCode 1.50.1
sudo: false
matrix:
  fast_finish: true
  allow_failures:
  - os: linux
  - os: windows
env:
  global:
    - YARN_GPG=no # https://travis-ci.community/t/build-doesnt-finish-after-completing-tests/288
#before_install:
#- if [ $TRAVIS_OS_NAME == "linux" ]; then
#    export CXX="g++-4.9" CC="gcc-4.9" DISPLAY=:99.0;
#    sh -e /etc/init.d/xvfb start;
#    sleep 3;
#  fi
install:
- yarn
- yarn vscode:install
- yarn vscode:prepublish
script:
- yarn test
notifications:
  email: false
