<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple Computer//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
  <dict>
    <key>name</key>
    <string>ARGUS H800 Assembly Language</string>
    <key>scopeName</key>
    <string>source.mitigus</string>
    <key>fileTypes</key>
    <array>
      <string>argus</string>
      <string>mitigus</string>
    </array>
    <key>uuid</key>
    <string>db04aa4b-b4b2-4e42-b9e6-3bb6ca2ecf6f</string>
    <key>patterns</key>
    <array>
      <dict>
        <key>comment</key>
        <string>Annotation comments</string>
        <key>name</key>
        <string>invalid.deprecated.mitigus</string>
        <key>match</key>
        <string>^#.*</string>
      </dict>
      <dict>
        <key>comment</key>
        <string>Annotation comments</string>
        <key>name</key>
        <string>invalid.deprecated.mitigus</string>
        <key>match</key>
        <string>^##.*</string>
      </dict>
      <dict>
        <key>comment</key>
        <string>Log Section cards.</string>
        <key>name</key>
        <string>comment.line.number-sign.mitigus</string>
        <key>match</key>
        <string>^L .*</string>
      </dict>
      <dict>
        <key>comment</key>
        <string>Source cards.</string>
        <key>name</key>
        <string>constant.numeric.mitigus</string>
        <key>match</key>
        <string>^ [0-9]+ *[*]?</string>
      </dict>
    </array>
  </dict>
</plist>
