name: Yarn
on: [pull_request]
jobs:
  yarn_lock_changes:
    name: Lock File Changes
    runs-on: ubuntu-latest
    # Permission overwrite is required for Dependabot PRs
    permissions:
      pull-requests: write
    steps:
      - name: Checkout
        uses: actions/checkout@v6
      - name: Digest Lock File
        uses: Simek/yarn-lock-changes@8dba8e6714613a8b96fd066bf5e9136b9b70d037
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          collapsibleThreshold: 25
          failOnDowngrade: false
          path: yarn.lock
          updateComment: true
